build-test:
  image: inf4/stubs:gcc-x64
  before_script:
    - apt-get update && apt-get install -y python3 python3-pyparsing
  script:
    - make
  artifacts:
    paths:
      - "elfo-*"

coding-style:
  image: inf4/stubs:clang-x64
  before_script:
    - apt-get update && apt-get install -y libc++-dev cpplint
  script:
    - make lint
    - make tidy