gcc:
  image: inf4/luci:ubuntu-jammy
  script:
    - make CXX=g++
  artifacts:
    paths:
      - "elfo-*"

gcc-dlh:
  image: inf4/luci:ubuntu-jammy
  before_script:
    - env
    - git clone ${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}/${CI_PROJECT_NAMESPACE}/dlh.git
    - make -C dlh LEGACY=1
  script:
    - make DLH=./dlh
  artifacts:
    paths:
      - "elfo-*"

clang:
  image: inf4/luci:ubuntu-jammy
  script:
    - make CXX=clang++ VERBOSE=
  artifacts:
    paths:
      - "elfo-*"

style:
  image: inf4/luci:ubuntu-jammy
  script:
    - make lint
    - make tidy
