gcc:
  image: inf4/luci:ubuntu-jammy
  script:
    - make
    - make test
  artifacts:
    paths:
      - "elfo-*"

clang:
  image: inf4/luci:ubuntu-jammy
  before_script:
    - update-alternatives --install /usr/bin/cc cc /usr/bin/clang-14 100
    - update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-14 100
  script:
    - make
    - make test
  artifacts:
    paths:
      - "elfo-*"

style:
  image: inf4/luci:ubuntu-jammy
  script:
    - make lint
    - make tidy
